[[redirects]]
  from = "https://talk2ai.netlify.app"
  to = "https://freeaichat.app"
  status = 301
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
