[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "https://talk2ai.netlify.app"
  to = "https://freeaichat.app"
  status = 301
  force = true
